version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-update
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RANDOM_ROOT_PASSWORD: false
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb-container
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - my_network

  emqx:
    image: emqx/emqx:latest
    container_name: emqx-container
    restart: always
    environment:
      EMQX_NAME: "emqx"
      EMQX_HOST: "0.0.0.0"
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_LISTENER__TCP__EXTERNAL: "1883"
      EMQX_LISTENER__SSL__EXTERNAL: "8883"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_logs:/opt/emqx/log
    networks:
      - my_network

volumes:
  mysql_data:
    driver: local
  influxdb_data:
    driver: local
  emqx_data:
    driver: local
  emqx_logs:
    driver: local

networks:
  my_network:
    driver: bridge
